# Generated by Django 2.2.26 on 2022-05-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220503_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isloggedin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
